### PR TITLE
map to severity level directly, since glossy supports numerical as well.

### LINKED ISSUE #33: Custom winston log levels submit 'false' to papertrail.
If a custom log level isn't an available Severity in glossy, the single word 'false' gets sent to papertrail.

### PR DESCRIPTION
**Pull request by bakavic**
Add map option for mapping npm levels to syslog severity. Fixes #33.

### CODE REVIEW

**Comment by conordickinson** [comment]
We really need this options as well, any idea when/if this will land?

**Comment by bakavic** [comment]
@kenperkins Is it usable in it's current state? Wouldn't mind some feedback ;)

**Comment by nathanmarks** [comment]
@bakavic Does this PR let me pass `silly` logs from winston to papertrail?

**Comment by bakavic** [comment]
@nathanmarks By default it clumps `debug` and `silly` under level 7, but you can modify the mapping by passing your own one in as an arg.

**Comment by nathanmarks** [comment]
@bakavic thanks!

**Comment by andyuk** [comment]
+1. Good fix - should be merged.

**Comment by troy** [comment]
This should be addressed in #48, which was merged into master a few minutes ago (and will become a versioned release if no one reports issues). If anyone has comments or sees downsides to #48 that are handled by this PR, please say so :)

**Comment by dmiddlecamp** [comment]
So it looks like the current module behavior now supports this PR intrinsically, but some names have changed:

npmLevelMap  -> is now "levels"
and "useNpmStyleLogLevels" is no longer necessarily since the level translation is always assumed

The only other key difference I see is that presently "verbose" is 7, instead of 6 (in this PR).  Is that okay?

I think if that difference is okay, we can close this PR without merging, since the behavior seems to have been added since this PR was submitted?

Thanks!
David

**Comment by bakavic** [comment]
Looks good to me! And the other PRs been merged already anyways ;)

**Pull request closed without merging**
