### PR TITLE
Version 2 rework

### PR DESCRIPTION
**Pull request by b5l**
I reworked the existing code on version 2. There were a lot of things from version 1 missing in this version, which I've added.

This is not perfect yet, but we're getting close to a releasable product, and I'm going to work more in it in the next couple of days. But I got most of the tests passing :)

Please have a look and tell me, what you think.

### CODE REVIEW

**Comment by ffxsam** [comment]
@benjaminlaib This is great, I'm sure people using winston-papertrail will appreciate this!

@kenperkins @troy Any thoughts?

**Comment by troy** [comment]
Thanks for all of your work, everyone!

@ffxsam I didn't know this codebase very well and am no longer affiliated with this project, so I'm afraid I'm not going to be of any use. I'm adding @markdascher to this thread in case he has any input. Good luck!

**Comment by b5l** [comment]
@ffxsam @markdascher Any news?

**Comment by ffxsam** [comment]
Looks OK to me, I'm fine with merging it! Any issues can easily be fixed later on, anyway.

**Pull request merged**
