### PR TITLE
Resolve #65 Add 'depth' option to limit the inspection depth of object

### LINKED ISSUE #65: Memory leak / endless loop
Using `util.inspect` without depth limit can cause memory leak / endless flooding in case an object has circular dependency 

lines `335`, `331` and `338`

```javascript
if (typeof(output) !== 'string') {
     output = util.inspect(output, false, null, self.colorize);
    }

    if (meta) {
        if (typeof meta !== 'object') {
            output += ' ' + meta;
        }
        else if (meta) {
            if (this.inlineMeta) {
                output += ' ' + util.inspect(meta, false, null, self.colorize).replace(/[\n\t]\s*/gm, " ");
            }
            else {
                output += '\n' + util.inspect(meta, false, null, self.colorize);
```

### PR DESCRIPTION
**Pull request by agoldis**

### CODE REVIEW

**Comment by agoldis** [comment]
@kenperkins

**Comment by agoldis** [comment]
@kenperkins ping! 😃

**Comment by troy** [comment]
@agoldis Thank you for considering that maintainers may not have seen this and trying to ensure they do. There's no need to do that, though. To set more reasonable and realistic expectations, @kenperkins and any other maintainers will act on this when they act on it.

**Comment by agoldis** [comment]
#65 is still an issue, seems like this project is abandoned :(

**Comment by troy** [comment]
Nope, not abandoned, just not staffed by a team of people. It has the same downsides as most open-source projects, which is to say, it's well-meaning people trying to do their best without merging PRs that could solve one problem but also may introduce others (or may not - more on that below). The hard part isn't clicking Merge, it's knowing that the code doesn't introduce other problems. We can't just merge anything freely, though, because 99% of this transport's users are actually happy.

Consulting https://github.com/kenperkins/winston-papertrail/pulls?q=is%3Apr+is%3Aclosed would also show conclusively that it's far from abandoned.

Regarding this PR, can you flesh out the details, like:

* what versions of node and/or winston have you tested this on, either once ("Well, mode still starts...") or by running in production?
* does it cause any new problems that you're aware of, or haven't checked but aren't sure of?

**Comment by agoldis** [comment]
@troy Thanks for your reply. 

I have invested my time to find the root cause of the issue and improve this open-source code, you are taking the responsibility and invest event more time by maintaining this project, trying to keep it safe and reliable.

I believe we all have a good intentions. 😃 

If the PR doesn't comply with project's contribution policies or introduces new issues, I would be glad to make reasonable changes or write tests or test manually in order to help and reduce uncertainty. It would be nice, though, to let me know that changes are required. 

As for the issue itself, it was discovered and tested in production systems running Ubuntu 16.04 LTS and NodeJS 5 and 6 versions (various versions). It changed code is being running for last 4 months on 8 Amazon-hosted machines.

I am not aware of any issues that this change might introduce, but there's a chance it can be a reason for some unexpected and unwanted behavior on some environments or software configurations.

**Comment by troy** [comment]
@agoldis fair points all around and I agree. This is an unusually conservative change, so I just merged this and [published v1.0.5](https://www.npmjs.com/package/winston-papertrail). Thank you for the contribution, too!

**Pull request merged**
